---
services:
  bind9:
    image: docker.io/ubuntu/bind9:9.20-24.10_edge
    container_name: bind9
    environment:
      - BIND9_USER=root
      - TZ=Europt/Berlin
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    restart: unless-stopped