---
services:
  prometheus:
    image: docker.io/prom/prometheus:v3.5.0
    container_name: prometheus
    user: 1000:1000
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.retention.time=7d
      - --storage.tsdb.retention.size=2GB
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./data:/prometheus
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    external: true