---
services:
  grafana:
    image: docker.io/grafana/grafana-oss:12.1.0
    container_name: grafana
    user: 1000:1000
    ports:
      - "3000:3000"
    volumes:
      - ./data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - backend
      - frontend

networks:
  backend:
    external: true
  frontend:
    external: true