version: '3.8'
x-common:
  database:
    &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_PASSWORD: &db-password "tim11235813"
    MYSQL_ROOT_PASSWORD: "tim11235813"
  panel:
    &panel-environment
    # This URL should be the URL that your reverse proxy routes to the panel server
    APP_URL: "https://pterodactyl.ta.ddnss.de"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "UTC"
    APP_SERVICE_AUTHOR: "noreply@example.com"
    TRUSTED_PROXIES: "*" # Set this to your proxy IP
    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
    # to generate an SSL certificate for the Panel.
    # LE_EMAIL: ""
  mail:
    &mail-environment
    MAIL_FROM: "noreply@example.com"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#
services:
  database:
    image: mariadb:10.5
    container_name: pterodactyl-database
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "/srv/docker-compose/pterodactyl/database:/var/lib/mysql"
    networks:
      - pterodactyl
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
  cache:
    image: redis:alpine
    container_name: pterodactyl-cache
    networks:
      - pterodactyl
    restart: always
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: pterodactyl-panel
    restart: always
    ports:
      - "5080:80"
      - "5443:443"
    links:
      - database
      - cache
    networks:
      - pterodactyl
    volumes:
      - "/srv/docker-compose/pterodactyl/var/:/app/var/"
      - "/srv/docker-compose/pterodactyl/nginx/:/etc/nginx/http.d/"
      - "/srv/docker-compose/pterodactyl/certs/:/etc/letsencrypt/"
      - "/srv/docker-compose/pterodactyl/logs/:/app/storage/logs"
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "pterodactyl-cache"
      DB_HOST: "pterodactyl-database"
      DB_PORT: "3306"
networks:
  pterodactyl:
    external: false

